apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: irctc-prod
    spec:
      containers:
      - name: demo-container
        image: 762989750451.dkr.ecr.us-east-1.amazonaws.com/eks-repo
        imagePullPolicy:
        ports:
        - containerPort: 80
